version: "3"
services:
  web-server: 
    container_name: web-server
    image: shkimm5189/djangoweb-python:v1
    command: "python3 manage.py runserver 0.0.0.0:8000"  
    links: 
    - "db-server"
    depends_on: 
      - db-server
  db-server:
    image: mysql:5.7
    container_name: db-server
    environment:
      - MYSQL_DATABASE=django_test
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - "mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
  ha-proxy:
    image: haproxy
    links:
      - "web-server"
    depends_on:
      - web-server
      - db-server
    volumes:
      - "./haproxy:/usr/local/etc/haproxy"
    ports:
      - "80:80"

volumes:
  mysql-data:
